create table if not exists public.wedding_tasks (
  id bigint generated by default as identity primary key,
  priority text not null check (priority in ('P1', 'P2', 'P3')),
  title text not null,
  owner text not null default '',
  target text not null default '',
  needed_info text not null default '',
  memo text not null default '',
  estimated_cost numeric,
  done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists wedding_tasks_updated_at on public.wedding_tasks;
create trigger wedding_tasks_updated_at
before update on public.wedding_tasks
for each row
execute function public.handle_updated_at();

alter table public.wedding_tasks enable row level security;

drop policy if exists "public read wedding tasks" on public.wedding_tasks;
create policy "public read wedding tasks"
on public.wedding_tasks
for select
using (true);

drop policy if exists "public insert wedding tasks" on public.wedding_tasks;
create policy "public insert wedding tasks"
on public.wedding_tasks
for insert
with check (true);

drop policy if exists "public update wedding tasks" on public.wedding_tasks;
create policy "public update wedding tasks"
on public.wedding_tasks
for update
using (true)
with check (true);

drop policy if exists "public delete wedding tasks" on public.wedding_tasks;
create policy "public delete wedding tasks"
on public.wedding_tasks
for delete
using (true);
