export const DEFAULT_TASKS = [
  {
    priority: "P1",
    title: "야외 스냅 촬영 예약",
    owner: "",
    target: "예식 5~7개월 전",
    neededInfo: "촬영 가능한 날짜 후보",
    memo: "예복/드레스, 메이크업, 헤어 포함 여부 확인",
    estimatedCost: 200,
    done: false,
  },
  {
    priority: "P1",
    title: "플래너",
    owner: "",
    target: "예식 6~7개월 전",
    neededInfo: "희망 예산, 진행 범위",
    memo: "견적 비교, 계약 조건 확인",
    estimatedCost: 250,
    done: false,
  },
  {
    priority: "P1",
    title: "본식 스냅 예약",
    owner: "",
    target: "예식 5~7개월 전",
    neededInfo: "예식장 정보, 희망 촬영 스타일",
    memo: "원본 제공, 보정, 앨범 포함 여부 확인",
    estimatedCost: 150,
    done: false,
  },
  {
    priority: "P1",
    title: "스드메 예약",
    owner: "다희",
    target: "예식 6~7개월 전",
    neededInfo: "희망 일정",
    memo: "스튜디오/드레스/메이크업 구성 확정",
    estimatedCost: 0,
    done: false,
  },
  {
    priority: "P2",
    title: "축가",
    owner: "성",
    target: "예식 3~4개월 전",
    neededInfo: "곡 후보",
    memo: "MR 준비, 리허설 일정 확인",
    estimatedCost: 20,
    done: false,
  },
  {
    priority: "P1",
    title: "항공권 예약",
    owner: "",
    target: "예식 6개월 전",
    neededInfo: "휴가 일정",
    memo: "수하물, 환불 규정 확인",
    estimatedCost: 600,
    done: false,
  },
  {
    priority: "P2",
    title: "한복 업체 예약",
    owner: "",
    target: "예식 3~5개월 전",
    neededInfo: "혼주 인원, 사이즈",
    memo: "대여/맞춤 선택, 제작기간 확인",
    estimatedCost: null,
    done: false,
  },
  {
    priority: "P2",
    title: "반지 구매",
    owner: "",
    target: "예식 4~6개월 전",
    neededInfo: "사이즈, 디자인",
    memo: "각인, 제작기간 확인",
    estimatedCost: null,
    done: false,
  },
  {
    priority: "P2",
    title: "혼주 메이크업",
    owner: "",
    target: "예식 2~3개월 전",
    neededInfo: "양가 인원, 희망 시간",
    memo: "양가 각각 예약 권장",
    estimatedCost: 80,
    done: false,
  },
  {
    priority: "P3",
    title: "관리",
    owner: "",
    target: "예식 1~2개월 전",
    neededInfo: "",
    memo: "마사지/피부과 등 일정 무리 없이",
    estimatedCost: null,
    done: false,
  },
  {
    priority: "P3",
    title: "미용",
    owner: "",
    target: "예식 1개월 전",
    neededInfo: "",
    memo: "커트/염색은 일정 여유 두기",
    estimatedCost: null,
    done: false,
  },
  {
    priority: "P1",
    title: "신혼여행 (항공권 제외)",
    owner: "",
    target: "예식 6개월 전",
    neededInfo: "숙소/투어 일정",
    memo: "취소 규정, 이동 동선 확인",
    estimatedCost: 600,
    done: false,
  },
];
